name: Garimpo de dados
title: Garimpo de dados
description: Um blog sobre como transformar dados em coisas úteis
meta_description: "Neste espaço você vai ler relatos de quem passa o tempo vasculhando dados pela internet afora. Acompanhe :)"
paginate_path: '/pagina/:num'
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

logo: false
baseurl: ''
paginate: 15
domain_name: 'http://henriquefreitas.com.br'
google_analytics: 'UA-87608325-3'
plugins: [jekyll-paginate, jekyll-auto-image]
repository: 'github.com/henriquefreitassouza/henriquefreitassouza.github.io'
excerpt_separator: <!--more-->

# Details for the RSS feed generator
url:            'http://henriquefreitas.com.br'
author:         'Henrique Freitas Souza'
