name: Some Data Blog
description: Do More With Your Data
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://henriquefreitas.com.br'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
repository: 'github.com/henriquefreitassouza/henriquefreitassouza.github.io'

# Details for the RSS feed generator
url:            'http://henriquefreitas.com.br'
author:         'Do More With Your Data'