name: Growth Value
description: Um blog que une pessoas e tecnologia
meta_description: "Neste espaço você vai ler histórias de um personagem que passa mais tempo buscando perguntas do que respostas. Acompanhe :)"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://henriquefreitas.com.br'
google_analytics: 'UA-87608325-3'
plugins: [jekyll-paginate, jekyll-auto-image]
repository: 'github.com/henriquefreitassouza/henriquefreitassouza.github.io'

# Details for the RSS feed generator
url:            'http://henriquefreitas.com.br'
author:         'Henrique Freitas Souza'
